FROM php:7.3-apache
COPY ./php.ini /usr/local/etc/php/
COPY ./fl4g_h1hih1i_xxx.txt /home/
RUN apt-get update \
  && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev libmcrypt-dev
